### ISSUE TITLE
[Request]Takeover the project

### ISSUE THREAD

**Issue by MSDNicrosoft** [joseph-garcia/macro-gui-buttons#7]
@joseph-garcia ,Hello
I found out that your project is no longer being maintained.
But this project is of great help to me.
So,Can I take over it please?

Here is the repository I created temporarily.
https://github.com/MSDNicrosoft/Command-GUI-Buttons

It is also posted at Modrinth at
https://modrinth.com/mod/command-gui-buttons

If you allow me to take it over, please ask if it is legal for me to mark your copyright information.
If you don't give me permission, I will automatically remove the content in question.

**Comment by MSDNicrosoft** [comment]
I'm not good at English :(
please understand

**Comment by joseph-garcia** [comment]
Hi, yes feel free to make a fork and make it your own! More power to open source :)

**Comment by MSDNicrosoft** [comment]
> Hi, yes feel free to make a fork and make it your own! More power to open source :)

thanks
